// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqcowwcqfabkwbxnhasz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxY293d2NxZmFia3dieG5oYXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNTY1MTksImV4cCI6MjA1NDYzMjUxOX0.ApzTYFWddvNE73uGxarZMCZOTwgXH2wW9hTkWVfomA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);